### ISSUE TITLE
Resynchronize action doesn’t check the group default

### ISSUE THREAD

**Issue by Galixte** [phpbb-extensions/autogroups#69]
Hi,

i think the "Resynchronize" action in "Manage Auto Groups" page in ACP should check the group default option if it’s set to "Yes".

**Comment by VSEphpbb** [comment]
Not sure what you are saying. The resync action is nothing special. It just triggers the normal functionality of the auto group. As normal, if set to yes, users will have that group made their default unless their default group is exempted from being changed.

**Comment by Galixte** [comment]
On my local forum (for tests) i have created two special groups:
- Banned
- VIP

With those groups i have set those options:
- Banned | Warnings | min value: 2 | max value: 0 | Group default: Yes | Notify users: Yes
- VIP | Posts | min value: 3 | max value: 0 | Group default: Yes | Notify users: Yes
- Set group default exemptions:
 - Banned: Yes
 - VIP: No
 - Registered users: No

With a new registered user, if he posts ten messages, he will have his default group set to the "VIP" group. Then, if he recieved two warnings, this user will have his default group set to "Banned" group. This user is always in "VIP" group. <= It's OK.

After one day (Auto Ban Duration) this user lose his default group "Banned" for the default group "Registered user". This user is always in VIP group. <= It's OK.

Me, as admin i want to synchronise the "VIP" group with the Synchronize button but the Resynchronization doesn't set the "VIP" group as default group for this user. <= It's not OK.

**Comment by VSEphpbb** [comment]
That's just a conflict in how you are using this. The user is already in VIP. A user can only have their default group changed when being added or removed from a group. 

The purpose of the synchronize button is to re-run auto groups on demand, for example if you just purged a ton of user posts, and resynced post counts, and need to resync post count based auto grouped users.

In other words, if you are setting up auto groups where users will be removed from a group then you have to understand the consequences of making those a default group, because they will lose it and go back to registered user when they are removed, which is just how phpBB handles removals.

In your example, the BAN group would be better *not* being set as a default (because they get removed from it eventually, after a day in your example). Normally the reason for adding to a group for warned users would be because you have some permission limitations on that group for while they are warned, for example, and there's no reason to make that their default.

**Comment by Galixte** [comment]
Yes i have done some permission limitations for BAN group. In my example, the reason for the BAN group becomes the default group is to attribute a default avatar and rank, just for that.

I have seen your previous NOTE posted:
```
EDIT: Or set up another auto group rule that removes them from the VIP group after getting those warnings, in addition to the rule you set up adding them to the BAN group based on those warnings. Once the warnings are gone, they will eventually be added back to VIP and regain that as their default.
```
And i have tested but unfortunately it’s not possible because there is a minimum value to set up that is not for the same condition.

It’s could be better to have the choice to set up two different conditions for minimum value and the maximum value, example:
- Group: VIP
- Auto Group type for min value: Posts
- Minimum value: 3
- Auto Group type for max value: Warnings
- Maximum value: 2

**Comment by VSEphpbb** [comment]
Basically what you are talking about is not possible because:

1. What if there are two or more groups that a user will still be a member of that are set to be default? Only a human being can decide which of those two should become their default.

2. If those resync buttons changed a users default group because it is set to yes, then users groups would always be changed whenever you use the resync. If a user is currently in VIP and BAN, and you resync BAN, BAN would become the default for all those users. Then if you resync VIP, any users also in BAN would be switched back to VIP for default.

As you can see, your scenario is not workable in an automated situation.
